apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: jenkins
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30942
  selector:
    app: jenkins
  type: NodePort