apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment-2
  namespace: k8s-demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30944
  selector:
    app: nginx
  type: NodePort